// <auto-generated />
namespace projeto.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _2d : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2d));
        
        string IMigrationMetadata.Id
        {
            get { return "202406011716426_2d"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
