@hostname = localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json
@apiKey = 5f80be92e8f94d79b3ac13d8a7d3c021
@validVin = XYZ1234567890

### 1. Send Message (Success)
POST https://{{host}}/api/message/{{validVin}}
x-api-key: {{apiKey}}
Content-Type: {{contentType}}

{
  "message": "cancelar encomenda",
  "sender": "Logistica"
}

### 2. Send Message (Invalid VIN)
POST https://{{host}}/api/message/INVALID_VIN
x-api-key: {{apiKey}}
Content-Type: {{contentType}}

{
  "message": "cancelar encomenda",
  "sender": "Logistica"
}

### 3. Send Message (Invalid API Key)
POST https://{{host}}/api/message/{{validVin}}
x-api-key: invalid-key
Content-Type: {{contentType}}

{
  "message": "cancelar encomenda",
  "sender": "Logistica"
}

### 4. Send Message (Missing API Key)
POST https://{{host}}/api/message/{{validVin}}
Content-Type: {{contentType}}

{
  "message": "cancelar encomenda",
  "sender": "Logistica"
}
