package com.example.myamover.ui.theme

import androidx.compose.ui.graphics.Color


val primaryLight = Color(0xFF2C7A2F)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF689F38)
val onPrimaryContainerLight = Color(0xFF374E14)
val secondaryLight = Color(0xFF93A184)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF77A873)
val onSecondaryContainerLight = Color(0xFF414A32)
val tertiaryLight = Color(0xFF33461D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFCAEEA6)
val onTertiaryContainerLight = Color(0xFF324E18)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFFFFF)
val onBackgroundLight = Color(0xFF1A1C16)
val surfaceLight = Color(0xFFFAFAEE)
val onSurfaceLight = Color(0xFF1A1C16)
val surfaceVariantLight = Color(0xFFE1E4D5)
val onSurfaceVariantLight = Color(0xFF45483D)
val outlineLight = Color(0xFF75786C)
val outlineVariantLight = Color(0xFFC5C8B9)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F312A)
val inverseOnSurfaceLight = Color(0xFFF1F2E6)
val inversePrimaryLight = Color(0xFFB4D088)
val surfaceDimLight = Color(0xFFDADBD0)
val surfaceBrightLight = Color(0xFFFAFAEE)
val surfaceContainerLowestLight = Color(0xFFEFF3ED)
val surfaceContainerLowLight = Color(0xFFF4F4E9)
val surfaceContainerLight = Color(0xFFEEEFE3)
val surfaceContainerHighLight = Color(0xFFE8E9DE)
val surfaceContainerHighestLight = Color(0xFF2D622D)



//Darkcolor
val primaryDark = Color(0xFFB4D088)
val onPrimaryDark = Color(0xFF213600)
val primaryContainerDark = Color(0xFF374E14)
val onPrimaryContainerDark = Color(0xFFCFEDA1)
val secondaryDark = Color(0xFFC0CAAC)
val onSecondaryDark = Color(0xFF2B331E)
val secondaryContainerDark = Color(0xFF414A32)
val onSecondaryContainerDark = Color(0xFFDCE7C7)
val tertiaryDark = Color(0xFFAFD18C)
val onTertiaryDark = Color(0xFF1D3703)
val tertiaryContainerDark = Color(0xFF324E18)
val onTertiaryContainerDark = Color(0xFFCAEEA6)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF12140E)
val onBackgroundDark = Color(0xFFE2E3D8)
val surfaceDark = Color(0xFF12140E)
val onSurfaceDark = Color(0xFFE2E3D8)
val surfaceVariantDark = Color(0xFF45483D)
val onSurfaceVariantDark = Color(0xFFC5C8B9)
val outlineDark = Color(0xFF8F9285)
val outlineVariantDark = Color(0xFF45483D)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E3D8)
val inverseOnSurfaceDark = Color(0xFF2F312A)
val inversePrimaryDark = Color(0xFF4E662A)
val surfaceDimDark = Color(0xFF12140E)
val surfaceBrightDark = Color(0xFF383A32)
val surfaceContainerLowestDark = Color(0xFF0D0F09)
val surfaceContainerLowDark = Color(0xFF1A1C16)
val surfaceContainerDark = Color(0xFF1E2019)
val surfaceContainerHighDark = Color(0xFF292B23)
val surfaceContainerHighestDark = Color(0xFF256E34)