MAPS_API_KEY= AIzaSyBE8jf-x8aq_n552q4cMaZdzoqwkkwmZ1E


SUPABASE_URL =https://qwowbaxkkinhnwneshnt.supabase.co
SUPABASE_ANON_KEY =sb_publishable_dj8DAizbcxiKzH6mR_I17Q_lde4MgyN

BASE_URL = "http:///" //colocar porta